#ifndef FAST_FSS_ERRORS_H
#define FAST_FSS_ERRORS_H

enum FastFssError
{
    FAST_FSS_SUCCESS                              = 0,
    FAST_FSS_RUNTIME_ERROR                        = -1,
    FAST_FSS_INVALID_KEY_DATA_SIZE_ERROR          = -2,
    FAST_FSS_INVALID_ALPHA_DATA_SIZE_ERROR        = -3,
    FAST_FSS_INVALID_BETA_DATA_SIZE_ERROR         = -4,
    FAST_FSS_INVALID_SEED_DATA_SIZE_ERROR         = -5,
    FAST_FSS_INVALID_BOUNDARY_DATA_SIZE_ERROR     = -6,
    FAST_FSS_INVALID_Z_DATA_SIZE_ERROR            = -7,
    FAST_FSS_INVALID_SHARED_OUT_DATA_SIZE_ERROR   = -8,
    FAST_FSS_INVALID_MASKED_X_DATA_SIZE_ERROR     = -9,
    FAST_FSS_INVALID_BITWIDTH_ERROR               = -10,
    FAST_FSS_INVALID_ELEMENT_SIZE_ERROR           = -11,
    FAST_FSS_INVALID_PARTY_ID_ERROR               = -12,
    FAST_FSS_INVALID_CACHE_DATA_SIZE_ERROR        = -13,
    FAST_FSS_INVALID_POINT_DATA_SIZE_ERROR        = -14,
    FAST_FSS_INVALID_LOOKUP_TABLE_DATA_SIZE_ERROR = -15,
    FAST_FSS_INVALID_GROUP_SIZE_ERROR             = -16,
    FAST_FSS_PRNG_INPUT_INVALID_ARGUMENT          = -17,
    FAST_FSS_PRNG_INVALID_BIT_WIDTH               = -18,
    FAST_FSS_PRNG_INVALID_ELEMENT_SIZE            = -19,
    FAST_FSS_PRNG_RANDOM_BUFFER_SIZE_TOO_SMALL    = -20,
};

#endif // FAST_FSS_ERRORS_H
